--- !ditz.rubyforge.org,2008-03-06/project 
name: CLS.git
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: CLS.git
- !ditz.rubyforge.org,2008-03-06/component 
  name: ObjectSystem
- !ditz.rubyforge.org,2008-03-06/component 
  name: StatModels
- !ditz.rubyforge.org,2008-03-06/component 
  name: Data
- !ditz.rubyforge.org,2008-03-06/component 
  name: Graphics
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-10 07:27:44.864923 Z
    - Tony <blindglobe@gmail.com>
    - created
    - release with ability to read in CSV files, descriptive numeric statistics, and linear regression
- !ditz.rubyforge.org,2008-03-06/release 
  name: "2.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-01-05 12:59:00.526366 Z
    - Tony <blindglobe@gmail.com>
    - created
    - future planning purposes
- !ditz.rubyforge.org,2008-03-06/release 
  name: "3.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-02-09 08:48:32.184740 Z
    - Tony <blindglobe@gmail.com>
    - created
    - staging ahead.
